"""
Chatterbox narration — the expressive British documentary voice.

Why this exists
---------------
The pipeline previously narrated with Kokoro-82M. It is fast and tiny, but it is also
the flattest voice measured: pitch variation 24.2 against 52.1 for the best edge-tts
voice and 58.6 for Chatterbox. Pitch variation is the objective proxy for "robotic vs
expressive" — a monotone read holds pitch nearly constant — and the flatness was the
main reason the videos sounded synthetic.

Chatterbox (Resemble AI, MIT) wins blind preference tests against ElevenLabs and adds
an explicit emotion control. Two things had to be solved to use it here:

  * Accent. Chatterbox defaults to an American voice, so a British male is cloned from
    a short reference clip. The reference is itself generated by edge-tts rather than
    taken from a real person, which avoids any consent or licensing question and lets
    CI rebuild it from scratch.
  * Truncation. Chatterbox silently cuts long input — the first samples stopped
    halfway through the script. Generation is therefore sentence by sentence, stitched
    with short pauses, which also gives the delivery documentary rhythm.

Measured on a free 4-core GitHub runner at roughly 4.3x realtime, so ~60s of narration
costs ~5 minutes. Falls back to the previous engine on any failure: the model is
generative and non-deterministic, and an unattended pipeline must not stall on a bad
take.
"""

import os
import re
import subprocess

from config import (
    AUDIO_DIR, CHATTERBOX_ENABLED, CHATTERBOX_REFERENCE,
    CHATTERBOX_EXAGGERATION, CHATTERBOX_CFG_WEIGHT, CHATTERBOX_SENTENCE_GAP,
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# A take shorter than this fraction of the expected duration means the model dropped
# most of the script. Cheap guard against shipping a half-finished narration.
_MIN_DURATION_RATIO = 0.55
_WORDS_PER_SECOND = 2.6          # measured pace of this narrator


def is_available() -> bool:
    if not CHATTERBOX_ENABLED:
        return False
    try:
        import torch  # noqa: F401
        import chatterbox  # noqa: F401
    except Exception:
        return False
    return os.path.exists(os.path.join(BASE_DIR, CHATTERBOX_REFERENCE))


def _sentences(text: str) -> list:
    """Split into sentences, merging fragments too short to generate cleanly."""
    parts = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]
    merged, buf = [], ""
    for p in parts:
        buf = f"{buf} {p}".strip() if buf else p
        if len(buf.split()) >= 4:      # very short fragments produce artefacts
            merged.append(buf)
            buf = ""
    if buf:
        if merged:
            merged[-1] = f"{merged[-1]} {buf}"
        else:
            merged.append(buf)
    return merged


def generate(text: str, filename_prefix: str = "doc") -> dict:
    """
    Narrate `text` and return the same shape as tts_generator.generate_tts:
        {audio_path, timings_path, word_timings, duration}

    Raises on failure so the caller can fall back — never returns partial audio.
    """
    import torch
    import torchaudio
    from chatterbox.tts import ChatterboxTTS
    from tts_generator import normalize_for_tts, _transcribe_for_timing

    ref = os.path.join(BASE_DIR, CHATTERBOX_REFERENCE)
    spoken = normalize_for_tts(text)      # numbers/years -> words, as before
    chunks_text = _sentences(spoken)
    if not chunks_text:
        # Belt and braces. An empty script once reached this point and torch.cat died
        # on an empty tensor list; the Kokoro fallback then failed on the same empty
        # text, so the run lost the video entirely. The generator now blocks empty
        # scripts upstream, but the narrator must not be the thing that explodes.
        raise RuntimeError("nothing to narrate — script is empty after normalisation")
    print(f"[Chatterbox] Narrating {len(chunks_text)} sentence(s) "
          f"as {os.path.basename(ref)}...")

    model = ChatterboxTTS.from_pretrained(device="cpu")

    pieces = []
    gap = torch.zeros(1, int(model.sr * CHATTERBOX_SENTENCE_GAP))
    for i, sentence in enumerate(chunks_text, 1):
        wav = model.generate(
            sentence,
            audio_prompt_path=ref,
            exaggeration=CHATTERBOX_EXAGGERATION,
            cfg_weight=CHATTERBOX_CFG_WEIGHT,
        )
        pieces.append(wav)
        if i < len(chunks_text):
            pieces.append(gap)
        print(f"[Chatterbox]   {i}/{len(chunks_text)}")

    full = torch.cat(pieces, dim=-1)
    duration = full.shape[-1] / model.sr

    expected = len(spoken.split()) / _WORDS_PER_SECOND
    if duration < expected * _MIN_DURATION_RATIO:
        raise RuntimeError(
            f"narration is {duration:.1f}s but the script needs ~{expected:.0f}s — "
            f"the model dropped content"
        )

    os.makedirs(AUDIO_DIR, exist_ok=True)
    wav_path = os.path.join(AUDIO_DIR, f"{filename_prefix}_chatterbox.wav")
    mp3_path = os.path.join(AUDIO_DIR, f"{filename_prefix}_chatterbox.mp3")
    torchaudio.save(wav_path, full, model.sr)

    # The rest of the pipeline expects mp3, and it is a fraction of the size.
    from video_composer import FFMPEG
    r = subprocess.run([FFMPEG, "-y", "-i", wav_path, "-codec:a", "libmp3lame",
                        "-b:a", "192k", mp3_path], capture_output=True)
    audio_path = mp3_path if r.returncode == 0 and os.path.exists(mp3_path) else wav_path

    # Word timings come from Whisper transcribing the finished audio, exactly as
    # before — it is engine-agnostic, so captions stay in sync with no extra work.
    # The script is handed over so captions show the words we wrote rather than
    # whatever the speech model thought it heard.
    word_timings = _transcribe_for_timing(audio_path, script=spoken)

    print(f"[Chatterbox] Done — {duration:.1f}s, {len(word_timings)} words timed.")
    return {
        "audio_path":   audio_path,
        "timings_path": None,
        "word_timings": word_timings,
        "duration":     duration,
    }
