"""
TikTok Auto-Uploader — @buriedcasefiles
Uploads finished documentary videos to TikTok using saved browser cookies.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FIRST-TIME SETUP (5 minutes, do this once):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Install Chrome extension "Get cookies.txt LOCALLY" by Rahul Shaw
   → https://chrome.google.com/webstore/detail/get-cookiestxt-locally/

2. Go to https://www.tiktok.com and log in to @buriedcasefiles

3. Click the extension icon → make sure you're on tiktok.com → click Export

4. Save the downloaded file as:
      C:\\Users\\maxwi\\youtube-automation\\tiktok_cookies.txt

5. Test it works:
      python tiktok_uploader.py --test

After that, every video generated by main_documentary.py will be
automatically uploaded to TikTok.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NOTE: Re-export cookies every ~2 weeks or after logging out of TikTok.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import os
import sys
import time
import json
from pathlib import Path

from config import (
    TIKTOK_HASHTAGS,
    TIKTOK_CAPTION_TEMPLATE,
    TIKTOK_COOKIES_FILE,
)

# Accept both .txt (Netscape format) and .json (EditThisCookie format)
_COOKIES_TXT  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tiktok_cookies.txt")
_COOKIES_JSON = TIKTOK_COOKIES_FILE   # tiktok_cookies.json


# ─── Internal helpers ──────────────────────────────────────────────────────────

def _find_cookies() -> str | None:
    """Return the path to a non-empty cookies file, or None."""
    for path in [_COOKIES_TXT, _COOKIES_JSON]:
        if os.path.exists(path) and os.path.getsize(path) > 20:
            return path
    return None


def _build_caption(title: str, story_hashtags: str) -> str:
    """Assemble the full TikTok caption (max 2200 chars)."""
    caption = TIKTOK_CAPTION_TEMPLATE.format(
        title=title,
        hashtags=TIKTOK_HASHTAGS,
        story_hashtags=story_hashtags,
    )
    return caption[:2200]


def _print_setup_instructions():
    print("""
[TikTok] --- SETUP REQUIRED ---
No session cookies found. To enable automatic TikTok uploads:

  1. Install Chrome extension:
       "Get cookies.txt LOCALLY" by Rahul Shaw
       https://chrome.google.com/webstore/detail/get-cookiestxt-locally/

  2. Log into https://www.tiktok.com as @buriedcasefiles

  3. Click the extension icon and export cookies for tiktok.com

  4. Save the file as:
       C:\\Users\\maxwi\\youtube-automation\\tiktok_cookies.txt

  5. Test: python tiktok_uploader.py --test

[TikTok] Skipping TikTok upload for now — video is saved locally.
""")


# ─── Main upload function ──────────────────────────────────────────────────────

def upload_to_tiktok(
    video_path:    str,
    title:         str,
    story_hashtags: str = "",
    retries:       int  = 2,
) -> bool:
    """
    Upload a video to TikTok.

    Args:
        video_path:      Absolute path to the .mp4 file
        title:           Video title (used in caption)
        story_hashtags:  Case-specific hashtags (e.g. "#Dyatlov #russia")
        retries:         How many times to retry on failure

    Returns:
        True on success, False on failure (non-fatal — pipeline continues)
    """
    cookies = _find_cookies()
    if cookies is None:
        _print_setup_instructions()
        return False

    try:
        from tiktok_uploader.upload import upload_video   # type: ignore
    except ImportError:
        print("[TikTok] tiktok-uploader not installed.")
        print("[TikTok] Run:  pip install tiktok-uploader")
        return False

    caption = _build_caption(title, story_hashtags)

    print(f"[TikTok] Uploading: {os.path.basename(video_path)}")
    print(f"[TikTok] Caption:   {caption[:100]}...")
    print(f"[TikTok] Cookies:   {os.path.basename(cookies)}")

    for attempt in range(1, retries + 1):
        try:
            upload_video(
                filename=video_path,
                description=caption,
                cookies=cookies,
            )
            print(f"[TikTok] Upload successful!")
            return True
        except Exception as e:
            print(f"[TikTok] Attempt {attempt}/{retries} failed: {e}")
            if attempt < retries:
                print("[TikTok] Retrying in 30s...")
                time.sleep(30)

    print("[TikTok] All upload attempts failed.")
    print(f"[TikTok] Upload manually: {video_path}")
    print("[TikTok] If cookies expired, re-export from your browser.")
    return False


# ─── CLI (for manual testing) ─────────────────────────────────────────────────

def _cli():
    import argparse
    p = argparse.ArgumentParser(
        description="TikTok uploader for @buriedcasefiles",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    p.add_argument("--test",  action="store_true",
                   help="Upload the most recently generated video as a test")
    p.add_argument("--video", type=str, default=None,
                   help="Upload a specific video file")
    p.add_argument("--title", type=str, default="True Crime Documentary",
                   help="Title to use in the caption")
    p.add_argument("--tags",  type=str, default="",
                   help="Extra hashtags (e.g. '#Dyatlov #russia')")
    args = p.parse_args()

    if args.test or args.video:
        if args.video:
            video = args.video
        else:
            # Find most recent video in output/
            output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")
            videos = sorted(Path(output_dir).glob("*.mp4"), key=os.path.getmtime, reverse=True)
            if not videos:
                print("[TikTok] No videos found in output/  — generate one first with main_documentary.py")
                sys.exit(1)
            video = str(videos[0])
            print(f"[TikTok] Using latest video: {os.path.basename(video)}")

        ok = upload_to_tiktok(video, args.title, args.tags)
        sys.exit(0 if ok else 1)
    else:
        p.print_help()


if __name__ == "__main__":
    _cli()
